//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorFutbol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
        public string Foto { get; set; }
        public string Posicion { get; set; }
        public Nullable<int> Equipo_ID { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
