//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorFutbol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partido()
        {
            this.Torneo_Partido = new HashSet<Torneo_Partido>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Equipo1 { get; set; }
        public Nullable<int> Equipo2 { get; set; }
        public string Direccion { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneo_Partido> Torneo_Partido { get; set; }
    }
}
